import React from "react";
import Navbar from "../navbar";
import "../globals.css";
import { Rethink_Sans } from "next/font/google";
import { Metadata } from "next";
import Footer from "../Footer";

const rethink = Rethink_Sans({
  variable: "--font-rethink-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${rethink.className} antialiased gap-y-12 tracking-tight text-white bg-zinc-950 flex flex-col`}
        >
          <Navbar />
          <main className="w-full flex-1 max-w-screen-xl mx-auto pb-5">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </>
  );
}
