import type { Metadata } from "next";
import { Geist, Geist_Mono, Rethink_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./Footer";

const rethink = Rethink_Sans({
  variable: "--font-rethink-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${rethink.className} antialiased gap-y-12 tracking-tight text-white bg-zinc-950`}
        >
          <Navbar />
          <main className="pb-10">{children}</main>
          <Footer />
        </body>
      </html>
    </>
  );
}
