import type { Metadata } from "next";
import { Rethink_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "../navbar";
import Footer from "../Footer";
import { ToastContainer } from "react-toastify";

const rethink = Rethink_Sans({
  variable: "--font-rethink-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Perya Gang",
    description: "Get Rewarded Like Never Before",
    // url: "https://perya-gang.vercel.app", // REPLACE THS WITH ACTUAL URL
    siteName: "Perya Gang",
    images: [
      {
        url: "",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${rethink.className} antialiased gap-y-12 tracking-tight text-white bg-zinc-950`}
        >
          <ToastContainer />
          <Navbar />
          <main className="pb-10">{children}</main>
          <Footer />
        </body>
      </html>
    </>
  );
}
